package wx

const MessageType_Text = "text"
const MessageType_Image = "image"
const MessageType_Voice = "voice"
const MessageType_Video = "video"
const MessageType_Music = "music"
const MessageType_News = "news"
const MessageType_Mpnews = "mpnews"
const MessageType_Msgmenu = "msgmenu"
const MessageType_Miniprogrampage = "miniprogrampage"
const MessageType_Wxcard = "wxcard"
const MessageType_Template = "template"
const MessageType_Link = "link"
const MessageType_TransferCustomerService = "transfer_customer_service"
const MessageType_Subscribe_Template = "subscribe_template"
