// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

/*
Package kk is a generated protocol buffer package.

It is generated from these files:
	Message.proto
	Request.proto
	Response.proto

It has these top-level messages:
	Message
	Request
	Response
*/
package kk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	// *
	// 来源地址
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// *
	// 目标地址
	To string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	// *
	// 数据类型
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	// *
	// 数据
	// @type {bytes}
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "kk.Message")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xce, 0x56, 0x0a, 0xe5,
	0x62, 0x87, 0x0a, 0x0a, 0x09, 0x71, 0xb1, 0xa4, 0x15, 0xe5, 0xe7, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0x7c, 0x5c, 0x4c, 0x25, 0xf9, 0x12, 0x4c, 0x60, 0x11, 0xa6, 0x92,
	0x7c, 0x90, 0x9a, 0x92, 0xca, 0x82, 0x54, 0x09, 0x66, 0x88, 0x1a, 0x10, 0x1b, 0x24, 0x96, 0x92,
	0x58, 0x92, 0x28, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x27, 0xb1, 0x81, 0x6d, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x53, 0xa0, 0x42, 0xb7, 0x72, 0x00, 0x00, 0x00,
}
